# Generated by Django 5.2.6 on 2025-09-15 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowrecord",
            name="student_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="borrowrecord",
            name="equipment",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="core.equipment",
            ),
            preserve_default=False,
        ),
    ]
