# Generated by Django 5.2.6 on 2025-09-09 13:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="checkinevent",
            index=models.Index(
                fields=["session_date", "facility"],
                name="core_checki_session_731f15_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="checkinevent",
            index=models.Index(
                fields=["facility", "occurred_at"],
                name="core_checki_facilit_d95bcb_idx",
            ),
        ),
    ]
